FROM node:alpine3.19
#create a aoo directory

WORKDIR /app

#Install App Dependencies

COPY package*.json ./

#run npm install

RUN npm install

#bundle app source

COPY . .

EXPOSE 5000

CMD ["npm","start"]
