FROM node
#create a aoo directory

WORKDIR /usr/src/app

#Install App Dependencies

COPY package*.json ./

#run npm install

RUN npm install --force

#bundle app source

COPY . .

EXPOSE 5000

CMD ["npm","start"]
